=== sj/fawkresrobotics-fawkes-copy/src/libs/interfaces/interface.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 *  DTD for Fawkes interfaces
 *
 *  Created: Wed Oct 11 00:57:30 2006
 *  Copyright  2006-2009  Tim Niemueller [www.niemueller.de]
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Library General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
-->
<!ELEMENT interface (constants?, data, message*)>
<!ATTLIST interface
	  name    CDATA  #REQUIRED
	  author  CDATA  #IMPLIED
	  created CDATA  #IMPLIED
	  year    CDATA  #IMPLIED>

  <!ELEMENT constants ((constant | enum)+)>
    <!ELEMENT constant (#PCDATA)>
    <!ATTLIST constant
	      type   CDATA  #REQUIRED
	      name   CDATA  #REQUIRED
	      value  CDATA  #REQUIRED>

    <!ELEMENT enum (comment, item+)>
    <!ATTLIST enum
	      name  CDATA  #REQUIRED>

      <!ELEMENT item (#PCDATA)>
      <!ATTLIST item
		name  CDATA  #REQUIRED>

  <!ELEMENT data (comment, (field | pseudomap | ref)+)>

    <!ELEMENT comment (#PCDATA)>

    <!ELEMENT pseudomap (comment, mapref+)>
    <!ATTLIST pseudomap
	      type      CDATA  #REQUIRED
	      keytype CDATA  #REQUIRED
	      name      CDATA  #REQUIRED>

    <!ELEMENT mapref (#PCDATA)>
    <!ATTLIST mapref
	      key      CDATA  #REQUIRED>

    <!ELEMENT field (#PCDATA)>
    <!ATTLIST field
	      type       CDATA  #REQUIRED
	      name       CDATA  #REQUIRED
	      flags      CDATA  #IMPLIED
	      length     CDATA  #IMPLIED
	      validfor   CDATA  '5'
	      default    CDATA  #IMPLIED
	      datafield  CDATA  #IMPLIED>

    <!ELEMENT ref (#PCDATA)>

  <!ELEMENT message (comment, (field | ref)*)>
  <!ATTLIST message
	    name  CDATA  #REQUIRED>

=== sj/fawkresrobotics-fawkes-copy/src/libs/interfaces/GripperInterface.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interface SYSTEM "interface.dtd">
<interface name="GripperInterface" author="Sebastian Reuter" year="2013">
  <constants>
    <enum name="GripperState">
      <comment>Indicator of current or desired gripper state.</comment>
      <item name="OPEN">Gripper is open</item>
      <item name="CLOSED">Gripper is closed</item>
    </enum>
  </constants>
  <data>
    <comment>
      This interface provides support for a simple gripper actuator.
      It has been used with the Robotino Gripper.
    </comment>
    <field type="GripperState" name="gripper_state">
      The current state of the gripper.
    </field>
  </data>
  <message name="OpenGripper">
    <comment>Request gripper to open.</comment>
  </message>
  <message name="CloseGripper">
    <comment>Request gripper to close.</comment>
  </message>
</interface>

=== sj/fawkresrobotics-fawkes-copy/src/plugins/robotino/interfaces/RobotinoSensorInterface.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interface SYSTEM "interface.dtd">
<interface name="RobotinoSensorInterface" author="Tim Niemueller" year="2012-2016">
  <data>
    <comment>Sensor information of a Robotino robot</comment>
    <field type="float" name="mot_velocity" length="3">Velocities of the wheels.</field>
    <field type="int32" name="mot_position" length="3">Positions of the wheels.</field>
    <field type="float" name="mot_current" length="3">Motor currents.</field>
    <field type="bool" name="bumper">Bumper pressed indicator.</field>
    <field type="float" name="distance" length="9">Distance sensor values.</field>
    <field type="bool" name="digital_in" length="8">Digital input values.</field>
    <field type="bool" name="digital_out" length="8">Digital output values.</field>
    <field type="float" name="analog_in" length="8">Analog input values.</field>
    <field type="bool" name="bumper_estop_enabled">
      True if emergency stop on bumper contact is enabled, false otherwise.
    </field>
  </data>

  <message name="SetBumperEStopEnabled">
    <comment>Sets the bumper state.</comment>
    <field type="bool" name="enabled">
      True to enable emergency stop on bumper contact, false to
      disable. This will persist over OpenRobotino stated restarts.
    </field>
  </message>

  <message name="SetDigitalOutput">
    <comment>Set a digital output.</comment>
    <field type="uint8" name="digital_out">
	    The number of the digital output to set.
    </field>
    <field type="bool" name="enabled">
      True to enable digital out, false to disable.
    </field>
  </message>

</interface>

=== sj/fawkresrobotics-fawkes-copy/src/libs/interfaces/LocalizationInterface.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interface SYSTEM "interface.dtd">
<interface name="LocalizationInterface" author="Tim Niemueller" year="2015">
  <data>
    <comment>
      Information and commands relevant to a self-localization
      component. This does not contain the pose as it is provided in a
      Position3DInterface.
    </comment>

    <field type="string" name="map" length="64">The currently used map.</field>
  </data>
  <message name="SetInitialPose">
    <comment>
      Set position of the object. Note that this is most likely not
      supported by the component writing the interface.
      This is compatible with the ROS' initialpose topic.
    </comment>
    <field type="string" length="32" name="frame">
      Reference coordinate frame for the data.
    </field>
    <field type="double" length="4" name="rotation">
      Rotation quaternion relative to reference frame, ordered as (x, y, z, w).
    </field>
    <field type="double" length="3" name="translation">
      Translation vector from the reference frame's origin, ordered as (x, y, z).
    </field>o
    <field type="double" name="covariance" length="36">
      Row-major representation of the 6x6 covariance matrix. The
      orientation parameters use a fixed-axis representation. In
      order, the parameters are: (x, y, z, rotation about X axis,
      rotation about Y axis, rotation about Z axis).
    </field>
  </message>
</interface>

=== sj/fawkresrobotics-fawkes-copy/src/libs/interfaces/TestInterface.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interface SYSTEM "interface.dtd">
<interface name="TestInterface" author="Tim Niemueller" year="2006-2007">
  <constants>
    <constant type="int32" value="5" name="TEST_CONSTANT">Just a test constant</constant>
    <constant type="float" value="1.2" name="TEST_FLOAT_CONSTANT">Another test constant</constant>
    <enum name="TestEnum">
      <comment>Demonstrating enums</comment>
      <item name="TEST_ENUM_1">Item 1</item>
      <item name="TEST_ENUM_2">Item 2</item>
    </enum>
  </constants>
  <data>
    <comment>Test interface. Use this to play around. Do NOT remove any fields, as this
      interface is used by BlackBoard QA.</comment>
    <field type="bool" name="test_bool">Test Bool</field>
    <field type="int32" name="test_int">Test integer</field>
    <field type="byte" name="flags">Flags spit down by the writer</field>
    <field type="string" length="30" flags="changed_indicator" validfor="5" default="testing default" name="test_string">A test sring</field>
    <field type="int32" name="result">Result of operation add operation from Calculate message.</field>
    <field type="uint32" name="test_uint">Test uint32</field>
    <!-- <field type="uint64" name="test_ulint">Test unsigned long int</field>
    <field type="int64" name="test_lint">Test long int</field> -->
  </data>
  <message name="SetTestInt">
    <comment>Set the test int to the given value.</comment>
    <ref>test_int</ref>
  </message>
  <message name="SetTestString">
    <comment>Set test string to this value.</comment>
    <ref>test_string</ref>
  </message>
  <message name="Calculate">
    <comment>Adds Summand and Addend. Result is put into Result field.</comment>
    <field type="int32" name="summand">Summand</field>
    <field type="int32" name="addend">Addend</field>
  </message>
</interface>

=== sj/fawkresrobotics-fawkes-copy/src/libs/interfaces/JoystickInterface.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interface SYSTEM "interface.dtd">
<interface name="JoystickInterface" author="Tim Niemueller" year="2008">
  <constants>
    <constant type="uint32" name="BUTTON_1" value="1">Button 1</constant>
    <constant type="uint32" name="BUTTON_2" value="2">Button 2</constant>
    <constant type="uint32" name="BUTTON_3" value="4">Button 3</constant>
    <constant type="uint32" name="BUTTON_4" value="8">Button 4</constant>
    <constant type="uint32" name="BUTTON_5" value="16">Button 5</constant>
    <constant type="uint32" name="BUTTON_6" value="32">Button 6</constant>
    <constant type="uint32" name="BUTTON_7" value="64">Button 7</constant>
    <constant type="uint32" name="BUTTON_8" value="128">Button 8</constant>
    <constant type="uint32" name="BUTTON_9" value="256">Button 9</constant>
    <constant type="uint32" name="BUTTON_10" value="512">Button 10</constant>
    <constant type="uint32" name="BUTTON_11" value="1024">Button 11</constant>
    <constant type="uint32" name="BUTTON_12" value="2048">Button 12</constant>
    <constant type="uint32" name="BUTTON_13" value="4096">Button 13</constant>
    <constant type="uint32" name="BUTTON_14" value="8192">Button 14</constant>
    <constant type="uint32" name="BUTTON_15" value="16384">Button 15</constant>
    <constant type="uint32" name="BUTTON_16" value="32768">Button 16</constant>
    <constant type="uint32" name="BUTTON_17" value="65536">Button 17</constant>
    <constant type="uint32" name="BUTTON_18" value="131072">Button 18</constant>
    <constant type="uint32" name="BUTTON_19" value="262144">Button 19</constant>
    <constant type="uint32" name="BUTTON_20" value="524288">Button 20</constant>
    <constant type="uint32" name="BUTTON_21" value="1048576">Button 21</constant>
    <constant type="uint32" name="BUTTON_22" value="2097152">Button 22</constant>
    <constant type="uint32" name="BUTTON_23" value="4194304">Button 23</constant>
    <constant type="uint32" name="BUTTON_24" value="8388608">Button 24</constant>
    <constant type="uint32" name="BUTTON_25" value="16777216">Button 25</constant>
    <constant type="uint32" name="BUTTON_26" value="33554432">Button 26</constant>
    <constant type="uint32" name="BUTTON_27" value="67108864">Button 27</constant>
    <constant type="uint32" name="BUTTON_28" value="134217728">Button 28</constant>
    <constant type="uint32" name="BUTTON_29" value="268435456">Button 29</constant>
    <constant type="uint32" name="BUTTON_30" value="536870912">Button 30</constant>
    <constant type="uint32" name="BUTTON_31" value="1073741824">Button 31</constant>
    <constant type="uint32" name="BUTTON_32" value="2147483648">Button 32</constant>

    <constant type="uint8" name="JFF_RUMBLE" value="1">Rumbling.</constant>
    <constant type="uint8" name="JFF_PERIODIC" value="2">Periodic force.</constant>
    <constant type="uint8" name="JFF_RAMP" value="4">Ramp effect.</constant>
    <constant type="uint8" name="JFF_SPRING" value="8">Simulate spring.</constant>
    <constant type="uint8" name="JFF_FRICTION" value="16">Sim. Friciton.</constant>
    <constant type="uint8" name="JFF_DAMPER" value="32">Simulate damper.</constant>
    <constant type="uint8" name="JFF_INERTIA" value="64">Simulate inertia.</constant>
    <constant type="uint8" name="JFF_CONSTANT" value="128">Constant force.</constant>

    <enum name="Direction">
      <comment>Effect direction.</comment>
      <item name="DIRECTION_DOWN" value="0">Down.</item>
      <item name="DIRECTION_LEFT" value="16384">Left.</item>
      <item name="DIRECTION_UP" value="32768">Up.</item>
      <item name="DIRECTION_RIGHT" value="49152">Right.</item>
    </enum>

  </constants>
  <data>
    <comment>
      This interface provides access to a joystick. It provides up to
      five axes, where each has a X and a Y value between -1.0 and 1.0.
      Up to 32 buttons are support via an uint32 bit field.
    </comment>
    <field type="byte" name="num_axes">
      The number of axes of this joystick
    </field>
    <field type="byte" name="num_buttons">
      The number of buttons of this joystick.
    </field>
    <field type="byte" name="supported_ff_effects">
      Bit field indicating available force-feedback effects.
    </field>
    <field type="uint32" name="pressed_buttons">
      A bit field of enabled buttons. For each currently clicked button the
      corresponding bit is set to 1. Use the BUTTON_* constants for bit-wise
      comparisons.
    </field>
    <field type="float" name="axis" length="8">Values of axes.</field>
    <field type="uint8" name="ff_effects">
      Currently running effects. Either 0 if no effect is running, or a bit-wise
      ored field of the JFF constants.
    </field>
  </data>
  <message name="StartRumble">
    <comment>Start joystick rumbling.</comment>
    <field type="uint16" name="length">Effect length in ms.
       Setting to 0 will make the effect to play continuously until stopped.
    </field>
    <field type="uint16" name="delay">Delay before effect starts in ms.</field>
    <field type="Direction" name="direction">Direction of effect</field>
    <field type="uint16" name="strong_magnitude">Magnitude of heavy motor.</field>
    <field type="uint16" name="weak_magnitude">Magnitude of light motor.</field>
  </message>
  <message name="StopRumble">
    <comment>Stop a specific effect.</comment>
  </message>
  <message name="StopAll">
    <comment>Stop all currently running effects.</comment>
  </message>
</interface>

=== sj/fawkresrobotics-fawkes-copy/src/libs/interfaces/HumanoidMotionInterface.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interface SYSTEM "interface.dtd">
<interface name="HumanoidMotionInterface" author="Tim Niemueller" year="2008">
  <constants>
    <enum name="LegEnum">
      <comment>Type to determinate leg side.</comment>
      <item name="LEG_LEFT">Left leg.</item>
      <item name="LEG_RIGHT">Right leg.</item>
    </enum>
    <enum name="StandupEnum">
      <comment>From which position to standup.</comment>
      <item name="STANDUP_DETECT">Detect via accelerometer.</item>
      <item name="STANDUP_BACK">Standup from lying on the back.</item>
      <item name="STANDUP_FRONT">Standup from lying on the tummy.</item>
    </enum>
  </constants>
  <data>
    <comment>
      This interface provides acces to basic humanoid motion patterns.
    </comment>

    <field type="bool" name="moving">True if the robot is moving.</field>
    <field type="bool" name="arms_enabled">
      If true the arms are controlled during walking for balancing.
    </field>

    <field type="uint32" name="msgid">
      The ID of the message that is currently being
      processed, or 0 if no message is being processed.
    </field>
  </data>

  <message name="Stop">
    <comment>Stop as soon as possible.</comment>
  </message>
  <message name="WalkStraight">
    <comment>Orders the robot to walk on a straight line.</comment>
    <field type="float" name="distance">Distance in m to walk.</field>
  </message>
  <message name="WalkSideways">
    <comment>Walk sideways (strafe).</comment>
    <field type="float" name="distance">Distance in m to walk.</field>
  </message>
  <message name="WalkArc">
    <comment>Orders the robot to walk on an arc.</comment>
    <field type="float" name="angle">Angle in radians to turn over the way.</field>
    <field type="float" name="radius">Radius in m of the circle in m.</field>
  </message>
  <message name="WalkVelocity">
    <comment>
      Orders the robot to walk with the given velocities. This is used
      for an omni-directional walk. It will stop if all velocities are 0.
    </comment>
    <field type="float" name="x">
      Fraction of MaxStepX. Use negative for backwards. [-1.0 to 1.0].
    </field>
    <field type="float" name="y">
      Fraction of MaxStepY. Use negative for right. [-1.0 to 1.0].
    </field>
    <field type="float" name="theta">
      Fraction of MaxStepTheta. Use negative for clockwise [-1.0 to 1.0].
    </field>
    <field type="float" name="speed">
      Fraction of MaxStepFrequency [0.0 to 1.0].
    </field>
  </message>
  <message name="Turn">
    <comment>Orders the robot to turn on the current position.</comment>
    <field type="float" name="angle">Angle in radians to turn.</field>
  </message>
  <message name="Kick">
    <comment>
      Kick with a robot's leg, for instance a ball.
    </comment>
    <field type="LegEnum" name="leg">Leg to kick with</field>
    <field type="float" name="strength">Kick strength</field>
  </message>
  <message name="Park">
    <comment>
      Bring robot into a park position where it is safe to turn servos off.
    </comment>
  </message>
  <message name="GetUp">
    <comment>Bring robot into a standing position when in park position.</comment>
  </message>
  <message name="Standup">
    <comment>Bring robot into a standing position when lying on the ground.</comment>
    <field type="StandupEnum" name="from_pos">Position from where to standup.</field>
  </message>
  <message name="MoveHead">
    <comment>Set head's pan/tilt to the given values..</comment>
    <field type="float" name="yaw">Desired yaw (horizontal orientation).</field>
    <field type="float" name="pitch">Desired pitch (vertical orientation).</field>
    <field type="float" name="speed">Maximum speed in [0.0..1.0].</field>
  </message>
</interface>

=== sj/fawkresrobotics-fawkes-copy/src/libs/interfaces/TransformInterface.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interface SYSTEM "interface.dtd">
<interface name="TransformInterface" author="Tim Niemueller" year="2011">
  <data>
    <comment>
      This interface is used to publish transforms. It aims to be as
      compatible as possible with ROS' tf library and is used
      extensively by the Fawkes tf library.

      For this to work properly it is crucial to have correct
      timestamp set (cf. Interface::set_timestamp()). Set this as
      close as possible to the time of when the data, from which the
      transform is computed, has been acquired.
    </comment>
    <field type="string" length="64" name="frame">
      Parent frame ID. The given transform is relative to the origin
      of this coordinate frame.
    </field>
    <field type="string" length="64" name="child_frame">
      The ID of the child frame. The child frame's origin is at the
      given point in the parent frame denoted by the transform.
    </field>
    <field type="bool" name="static_transform">
	    True if the transform is static, i.e. it will never change
	    during its lifetime, false otherwise.
    </field>
    <field type="double" length="3" name="translation">
      This array denotes the translation vector of the transform. The
      element indexes are ordered x, y, z, i.e. translation[0] is the
      X value of the translation vector.
    </field>
    <field type="double" length="4" name="rotation">
      This array denotes the rotation quaternion of the transform. The
      element indexes are ordered x, y, z, w, i.e. translation[0] is
      the X value of the rotation quaternion and translation[3] is the
      W value.
    </field>
  </data>
</interface>

=== sj/fawkresrobotics-fawkes-copy/src/libs/interfaces/IMUInterface.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interface SYSTEM "interface.dtd">
<interface name="IMUInterface" author="Tim Niemueller" year="2014">
  <data>
    <comment>
      This interface provides access to data of inertial measurement
      units. It is based on the sensor_msgs/Imu data type for
      compatibility.

      Accelerations should be in m/s^2 (not in g's), and rotational
      velocity should be in rad/sec.

      If the covariance of the measurement is known, it should be
      filled in (if all you know is the variance of each measurement,
      e.g. from the datasheet, just put those along the diagonal). A
      covariance matrix of all zeros will be interpreted as
      "covariance unknown", and to use the data a covariance will have
      to be assumed or gotten from some other source.

      If you have no estimate for one of the data elements (e.g. your
      IMU doesn't produce an orientation # estimate), please set
      element 0 of the associated covariance matrix to -1. If you are
      interpreting this message, please check for a value of -1 in the
      first element of each covariance matrix, and disregard the
      associated estimate.
    </comment>

    <field type="string" length="32" name="frame">
      Coordinate frame in which the data is presented.
    </field>
    <field type="float" length="4" name="orientation">
      Rotation quaternion ordered as (x, y, z, w).
    </field>
    <field type="double" length="9" name="orientation_covariance">
      Covariance of orientation, row major about x, y, z axes.
    </field>

    <field type="float" length="3" name="angular_velocity">
      Angular velocities ordered as (x, y, z).
    </field>
    <field type="double" length="9" name="angular_velocity_covariance">
      Covariance of angular velocity, row major about x, y, z axes.
    </field>

    <field type="float" length="3" name="linear_acceleration">
      Linear acceleration ordered as (x, y, z).
    </field>
    <field type="double" length="9" name="linear_acceleration_covariance">
      Covariance of linear acceleration, row major about x, y, z axes.
    </field>

  </data>
</interface>
