=== sj/fawkresrobotics-fawkes-copy/src/libs/interfaces/interface.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 *  DTD for Fawkes interfaces
 *
 *  Created: Wed Oct 11 00:57:30 2006
 *  Copyright  2006-2009  Tim Niemueller [www.niemueller.de]
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Library General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
-->
<!ELEMENT interface (constants?, data, message*)>
<!ATTLIST interface
	  name    CDATA  #REQUIRED
	  author  CDATA  #IMPLIED
	  created CDATA  #IMPLIED
	  year    CDATA  #IMPLIED>

  <!ELEMENT constants ((constant | enum)+)>
    <!ELEMENT constant (#PCDATA)>
    <!ATTLIST constant
	      type   CDATA  #REQUIRED
	      name   CDATA  #REQUIRED
	      value  CDATA  #REQUIRED>

    <!ELEMENT enum (comment, item+)>
    <!ATTLIST enum
	      name  CDATA  #REQUIRED>

      <!ELEMENT item (#PCDATA)>
      <!ATTLIST item
		name  CDATA  #REQUIRED>

  <!ELEMENT data (comment, (field | pseudomap | ref)+)>

    <!ELEMENT comment (#PCDATA)>

    <!ELEMENT pseudomap (comment, mapref+)>
    <!ATTLIST pseudomap
	      type      CDATA  #REQUIRED
	      keytype CDATA  #REQUIRED
	      name      CDATA  #REQUIRED>

    <!ELEMENT mapref (#PCDATA)>
    <!ATTLIST mapref
	      key      CDATA  #REQUIRED>

    <!ELEMENT field (#PCDATA)>
    <!ATTLIST field
	      type       CDATA  #REQUIRED
	      name       CDATA  #REQUIRED
	      flags      CDATA  #IMPLIED
	      length     CDATA  #IMPLIED
	      validfor   CDATA  '5'
	      default    CDATA  #IMPLIED
	      datafield  CDATA  #IMPLIED>

    <!ELEMENT ref (#PCDATA)>

  <!ELEMENT message (comment, (field | ref)*)>
  <!ATTLIST message
	    name  CDATA  #REQUIRED>

=== sj/fawkresrobotics-fawkes-copy/src/libs/interfaces/SoccerPenaltyInterface.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interface SYSTEM "interface.dtd">
<interface name="SoccerPenaltyInterface" author="Tim Niemueller" year="2008-2010">
  <constants>
    <!-- SPL game states -->
    <constant type="uint16" value="0" name="SPL_PENALTY_NONE">Not penalized.</constant>
    <constant type="uint16" value="1" name="SPL_PENALTY_BALL_HOLDING">Ball holding.</constant>
    <constant type="uint16" value="2" name="SPL_PENALTY_PLAYER_PUSHING">Player pushing.</constant>
    <constant type="uint16" value="3" name="SPL_PENALTY_OBSTRUCTION">Obstruction.</constant>
    <constant type="uint16" value="4" name="SPL_PENALTY_INACTIVE_PLAYER">Inactive player.</constant>
    <constant type="uint16" value="5" name="SPL_PENALTY_ILLEGAL_DEFENDER">Illegal defender.</constant>
    <constant type="uint16" value="6" name="SPL_PENALTY_LEAVING_THE_FIELD">Leaving the field.</constant>
    <constant type="uint16" value="7" name="SPL_PENALTY_PLAYING_WITH_HANDS">Playing with hands.</constant>
    <constant type="uint16" value="8" name="SPL_PENALTY_REQ_FOR_PICKUP">Request for pickup.</constant>
    <constant type="uint16" value="15" name="SPL_PENALTY_MANUAL">Manually penalized.</constant>
  </constants>
  <data>
    <comment>
      This interface stores penalization information for soccer robots.
      Currently it contains constants used in the RoboCup Standard Platform
      League (SPL).
    </comment>
    <field type="uint16" name="penalty">Current penalty code.</field>
    <field type="uint16" name="remaining">Estimated time in seconds until the robot is unpenalized.</field>
  </data>
  <message name="SetPenalty">
    <comment>Set penalty code. Can be used by the agent to override the value
     received from the refbox.</comment>
    <ref>penalty</ref>
  </message>
</interface>

=== sj/fawkresrobotics-fawkes-copy/src/plugins/perception/pcl-db/interfaces/PclDatabaseStoreInterface.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interface SYSTEM "interface.dtd">
<interface name="PclDatabaseStoreInterface" author="Tim Niemueller" year="2012-2014">
  <data>
    <comment>
      Instruct the pcl-db-store plugin.
    </comment>
    <field type="uint32" name="msgid">
      The ID of the message that is currently being processed, or 0 if
      no message is being processed.
    </field>
    <field type="bool" name="final">
      True, if the last goto command has been finished, false if it is
      still running.
    </field>
    <field type="string" length="256" name="error">
      Error description if reconstruction fails.
    </field>
  </data>
  <message name="Store">
    <comment>Order storing a point cloud.</comment>
    <field type="string" length="64" name="pcl_id">
      ID of the point cloud to store.
    </field>
    <field type="string" length="64" name="database">
      Database name from which to read the point clouds. If empty will
      use plugin-configured default.
    </field>
    <field type="string" length="128" name="collection">
      Collection name from which to read the point clouds. May NOT
      include the database name.
    </field>
  </message>
</interface>

=== sj/fawkresrobotics-fawkes-copy/src/libs/interfaces/FacialExpressionInterface.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interface SYSTEM "interface.dtd">
<interface name="FacialExpressionInterface" author="Bahram Maleki-Fard" year="2009">
  <constants>
    <enum name="brows_t">
      <comment>Action types for moving brows</comment>
      <item name="BROWS_DEFAULT">Reset</item>
      <item name="BROWS_FROWN">Frown</item>
      <item name="BROWS_LIFT">Lift</item>
    </enum>
    <enum name="eyes_t">
      <comment>Action types for moving eyes</comment>
      <item name="EYES_DEFAULT">Reset</item>
      <item name="EYES_UP">Up</item>
      <item name="EYES_DOWN">Down</item>
      <item name="EYES_LEFT">Left</item>
      <item name="EYES_RIGHT">Right</item>
      <item name="EYES_COOL">Cool</item>
      <item name="EYES_CROSS">Cross</item>
      <item name="EYES_HEART">Heart</item>
      <item name="EYES_DOLLAR">Dollar</item>
    </enum>
    <enum name="jowl_t">
      <comment>Action types for moving jowl</comment>
      <item name="JOWL_DEFAULT">Reset</item>
      <item name="JOWL_BLUSH">Blush</item>
      <item name="JOWL_TEARS">Tears</item>
    </enum>
    <enum name="mouth_t">
      <comment>Action types for moving mouth</comment>
      <item name="MOUTH_DEFAULT">Reset</item>
      <item name="MOUTH_OPEN">Open</item>
      <item name="MOUTH_CLOSE">Close</item>
      <item name="MOUTH_SMILE">Smile</item>
      <item name="MOUTH_SCOWL">Scowl</item>
    </enum>
  </constants>
  <data>
    <comment>
      Interface to acces facial expressions on display (RCSoft)
    </comment>
    <field type="brows_t" name="brows_action">Type of action of brows</field>
    <field type="eyes_t" name="eyes_action">Type of action of eyes</field>
    <field type="jowl_t" name="jowl_action">Type of action of jown</field>
    <field type="mouth_t" name="mouth_action">Type of action of mouth</field>
  </data>
  <message name="MoveBrows">
    <comment>Move brows</comment>
    <ref>brows_action</ref>
  </message>
  <message name="MoveEyes">
    <comment>Move eyes</comment>
    <ref>eyes_action</ref>
  </message>
  <message name="MoveJowl">
    <comment>Move brows</comment>
    <ref>jowl_action</ref>
  </message>
  <message name="MoveMouth">
    <comment>Move brows</comment>
    <ref>mouth_action</ref>
  </message>
</interface>

=== sj/fawkresrobotics-fawkes-copy/src/plugins/perception/pcl-db/interfaces/PclDatabaseMergeInterface.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interface SYSTEM "interface.dtd">
<interface name="PclDatabaseMergeInterface" author="Tim Niemueller" year="2012">
  <data>
    <comment>
      Instruct the pcl-db-merge plugin and receive information.
    </comment>
    <field type="uint32" name="msgid">
      The ID of the message that is currently being processed, or 0 if
      no message is being processed.
    </field>
    <field type="bool" name="final">
      True, if the last goto command has been finished, false if it is
      still running.
    </field>
    <field type="string" length="256" name="error">
      Error description if reconstruction fails.
    </field>
  </data>
  <message name="Merge">
    <comment>Order the merging of point clouds</comment>
    <field type="int64" name="timestamps" length="12">
      Timestamps for which to retrieve the most recent point clouds
      and merge them.
    </field>
    <field type="string" length="64" name="database">
      Database name from which to read the point clouds. If empty will
      use plugin-configured default.
    </field>
    <field type="string" length="128" name="collection">
      Collection name from which to read the point clouds. May NOT
      include the database name.
    </field>
  </message>
</interface>

=== sj/fawkresrobotics-fawkes-copy/src/plugins/laser-lines/interfaces/LaserLineInterface.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interface SYSTEM "interface.dtd">
<interface name="LaserLineInterface" author="Tim Niemueller" year="2013">
  <data>
    <comment>Line parameterization.</comment>
    <field type="string" length="32" name="frame_id">
      Coordinate frame ID of data.
    </field>
    <field type="int32" name="visibility_history">
      The visibilitiy history indicates the number of consecutive positive or negative
      sightings. If the history is negative, there have been as many negative sightings
      (object not visible) as the absolute value of the history. A positive value denotes
      as many positive sightings. 0 shall only be used during the initialization of the
      interface or if the visibility history is not updated.
    </field>
    <field type="float" length="3" name="point_on_line">
      Vector to some point on the line
    </field>
    <field type="float" length="3" name="line_direction">
      Vector in the direction of the line.
    </field>
    <field type="float" name="bearing">
      Direction towards the line, i.e. if the robot turns by this
      angle the robot will stand parallel to the line.
    </field>
    <field type="float" length="3" name="end_point_1">
      3D coordinates in the reference frame of one endpoint of the
      line. The end points are ordered arbitrarily.
    </field>
    <field type="float" length="3" name="end_point_2">
      3D coordinates in the reference frame of the second endpoint of
      the line.
    </field>
    <field type="float" name="length">Length of the line.</field>
    <field type="string" length="32" name="end_point_frame_1">
      Coordinate frame ID representing first endpoint's identity
    </field>
    <field type="string" length="32" name="end_point_frame_2">
      Coordinate frame ID representing second endpoint's identity
    </field>
  </data>
</interface>

=== sj/fawkresrobotics-fawkes-copy/src/libs/interfaces/MotorInterface.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interface SYSTEM "interface.dtd">
<interface name="MotorInterface" author="Martin Liebenberg, Tim Niemueller" year="2007">
  <constants>
    <constant type="uint32" name="MOTOR_ENABLED" value="0">
      Motor is enabled and sending drive commands will make the robot move.
    </constant>
    <constant type="uint32" name="MOTOR_DISABLED" value="1">
      Motor is disabled. Sending of drive commands is accepted but the robot will NOT
      move.
    </constant>
    <constant type="uint32" name="DRIVE_MODE_RPM" value="1">
      Motor drives in DriveRPM mode.
    </constant>
    <constant type="uint32" name="DRIVE_MODE_TRANS" value="2">
      Motor drives in Trans mode.
    </constant>
    <constant type="uint32" name="DRIVE_MODE_ROT" value="3">
      Motor drives in Rot mode.
    </constant>
    <constant type="uint32" name="DRIVE_MODE_TRANS_ROT" value="4">
      Motor drives in TransRot mode.
    </constant>
    <constant type="uint32" name="DRIVE_MODE_ORBIT" value="5">
      Motor drives in Orbit mode.
    </constant>
    <constant type="uint32" name="DRIVE_MODE_LINE_TRANS_ROT" value="6">
      Motor drives in LinTransRot mode.
    </constant>
  </constants>
  <data>
    <comment>This interface is currently prepared best for a holonomic robot.
      It will need modifications or a split to support differential drives.
    </comment>
    <field type="uint32" name="motor_state">
      The current state of the motor.
    </field>
    <field type="uint32" name="drive_mode">
      The current drive mode of the motor.
    </field>
    <field type="int32" name="right_rpm">
      RPM of the motor on the right front of the robot.
    </field>
    <field type="int32" name="rear_rpm">
      RPM of motor on the rear of the robot.
    </field>
    <field type="int32" name="left_rpm">
      RPM of the motor on the left front of the robot.
    </field>
    <field type="float" name="odometry_path_length">
      The actual length of the robot's trajectory since the last ResetOdometry.
    </field>
    <field type="float" name="odometry_position_x">
      The actual position of the robot relative to the position at the last ResetOdometry.
    </field>
    <field type="float" name="odometry_position_y">
      The actual position of the robot relative to the position at the last ResetOdometry.
    </field>
    <field type="float" name="odometry_orientation">
      The actual orientation of the robot relative to the orientation at the last ResetOdometry.
    </field>
    <field type="float" name="vx">
      VX of the robot in m/s. Forward.
    </field>
    <field type="float" name="vy">
      VY of the robot in m/s. Left.
    </field>
    <field type="float" name="omega">
      Rotation speed of the robot in rad/s.
    </field>
    <field type="float" name="des_vx">
      Desired VX of the robot in m/s. Forward.
    </field>
    <field type="float" name="des_vy">
      Desired VY of the robot in m/s. Left.
    </field>
    <field type="float" name="des_omega">
      Desired Rotation speed of the robot in rad/s.
    </field>
    <field type="uint32" name="controller">
     The ID of the controller. The controller ID is the instance serial of the sending
     interface. Only from this interface instance command messages are accepted.
    </field>
    <field type="string" length="64" name="controller_thread_name">
     The name of the controlling thread, for easier debugging. This is informative only
     and actually two threads may share an interface instance (although this should be
     avoided since the interface locking has to be reproduced for these threads then).
  </field>
  </data>
  <message name="SetMotorState">
    <comment>Sets the current motor state.</comment>
    <field type="uint32" name="motor_state">
      The new motor state to set. Use the MOTOR_* constants.
    </field>
  </message>
  <message name="AcquireControl">
    <comment>This allows any thread to aquire the control over the motor thread.
      Use with extreme care!</comment>
    <ref>controller</ref>
    <ref>controller_thread_name</ref>
  </message>
  <message name="ResetOdometry">
    <comment>Resets the the odometry. It sets OdometryDistance, OdometryPositionX,
      OdometryPositionY and OdometryOrientation to zero.</comment>
  </message>
  <message name="SetOdometry">
    <comment>Sets the odometry. It sets OdometeyPositionX,OdometryPositionY and OdometryOrientation based on given translation and new OdometryOrientation.</comment>
    <field type="float" name="x">Translation in x direction in m</field>
    <field type="float" name="y">Translation in y direction in m</field>
    <field type="float" name="odometry_orientation">OdometryOrientation in m</field>
  </message>
  <message name="DriveRPM">
    <comment>Directly set RPM, used for debugging, only use if you know what
             you are doing. Usage is discouraged.</comment>
    <field type="float" name="front_right">Rotation in RPM of the right front wheel.</field>
    <field type="float" name="front_left">Rotation in RPM of the left front wheel.</field>
    <field type="float" name="rear">Rotation in RPM of the rear wheel.</field>
  </message>
  <message name="Goto">
    <comment>Translate and rotate the robot to the given relative position. The
      provider may choose to translate this message into a TransRotMessage and
      process it accordingly.</comment>
    <field type="float" name="x">X distance in m.</field>
    <field type="float" name="y">Y distance in m.</field>
    <field type="float" name="phi">Angle relative to current angle in rad.</field>
    <field type="float" name="time_sec">When to reach the desired location.</field>
  </message>
  <message name="Trans">
    <comment>Translate the robot by the given velocities in X/Y direction.</comment>
    <field type="float" name="vx">Speed in X direction in m/s.</field>
    <field type="float" name="vy">Speed in Y direction in m/s.</field>
  </message>
  <message name="Rot">
    <comment>Rotate the robot by the given angle speed in rad/s (positive right).</comment>
    <field type="float" name="omega">Angle rotation in rad/s.</field>
  </message>
  <message name="TransRot">
    <comment>Translate and rotate the robot at the same time. This is the same as combining a
             Trans and a Rot message separately. Note that the robot will not drive on a line
             with VX/VY and then rotate by Omega. Instead the movements are superpositioned
             which will result in a curve. Use LinTransRot if you want this behaviour.</comment>
    <field type="float" name="vx">Speed in X direction in m/s.</field>
    <field type="float" name="vy">Speed in Y direction in m/s.</field>
    <field type="float" name="omega">Angle rotation in rad/s.</field>
  </message>
  <message name="Orbit">
    <comment>Orbit around a point. This will make the robot move in a circle around the given
             point (PX, PY) with the angular speed Omega. With Orbit the robot will not
             change its orientation and thus it will not focus on the point.</comment>
    <field type="float" name="px">Point's X coordinate to orbit.</field>
    <field type="float" name="py">Point's Y coordinate to orbit.</field>
    <field type="float" name="omega">Angular speed around point in rad/s.</field>
  </message>
  <message name="LinTransRot">
    <comment>Move along a line with given speed VX/VY and rotate the robot with Omega.</comment>
    <field type="float" name="vx">Speed for translation in X direction in m/s.</field>
    <field type="float" name="vy">Speed for translation in Y direction in m/s.</field>
    <field type="float" name="omega">Rotational speed in rad/s.</field>
  </message>
  <!-- needs sensor feedback, delayed
  <message name="OrbitRot">
    <comment>Orbit around a point and rotate the robot whilst doing so. This is
             the superpositioned movement of Orbit and Rot, while the orbiting is
       recalculated to make a circle and take the changed rotation into account.</comment>
    <field type="float" name="px">Point's X coordinate to orbit.</field>
    <field type="float" name="py">Point's Y coordinate to orbit.</field>
    <field type="float" name="omega_orbit">Angular speed around point in rad/s.</field>
    <field type="float" name="omega_rot">Angular speed of the robot's rotation in rad/s.</field>
  </message>
  <message name="TransOrbit">
    <comment>Translate with the given speed and keep looking at the given point.</comment>
    <field type="float" name="vx">Speed for translation in X direction in m/s.</field>
    <field type="float" name="vy">Speed for translation in Y direction in m/s.</field>
    <field type="float" name="px">Point's X coordinate to focus.</field>
    <field type="float" name="py">Point's Y coordinate to focus.</field>
  </message>
  --><!-- maby name TransOrbit TransAim -->
</interface>

=== sj/fawkresrobotics-fawkes-copy/src/plugins/laser-filter/interfaces/LaserBoxFilterInterface.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interface SYSTEM "interface.dtd">
<interface name="LaserBoxFilterInterface" author="Nicolas Limpert" year="2018">
  <data>
    <field type="uint32" name="num_boxes">The number of currently applied boxes</field>
    <comment>
      Interface to create new laser filters at runtime.
    </comment>
    <!-- Raw data output from servo -->
  </data>

  <!-- Motion commands -->
  <message name="CreateNewBoxFilter">
    <comment>Create a new filter.</comment>
    <field type="double" length="2" name="p1">x,y coordinates of first vector</field>
    <field type="double" length="2" name="p2">x,y coordinates of second vector</field>
    <field type="double" length="2" name="p3">x,y coordinates of third vector</field>
    <field type="double" length="2" name="p4">x,y coordinates of fourth vector</field>
  </message>
</interface>

=== sj/fawkresrobotics-fawkes-copy/src/libs/interfaces/LedInterface.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interface SYSTEM "interface.dtd">
<interface name="LedInterface" author="Tim Niemueller" year="2008">
  <constants>
    <constant type="float" name="ON" value="1.0">Turn LED on.</constant>
    <constant type="float" name="OFF" value="0.0">Turn LED off.</constant>
  </constants>
  <data>
    <comment>
      This interface provides access to LEDs. The interface controls an
      intensity value between 0.0 (off) and 1.0 (on, max intensity). LEDs
      that do not support intensity setting can only be set to on and off.
    </comment>
    <field type="float" name="intensity">Intensity value.</field>
  </data>
  <message name="SetIntensity">
    <comment>Sets a new intensity on the LED.</comment>
    <ref>intensity</ref>
    <field type="float" name="time_sec">
      Time in seconds when to reach the intensity.
    </field>
  </message>
  <message name="TurnOn">
    <comment>Turns the LED on to maximum intensity immediately.</comment>
  </message>
  <message name="TurnOff">
    <comment>Turns the LED off immediately.</comment>
  </message>
</interface>
