=== sj/fawkresrobotics-fawkes-copy/src/libs/interfaces/interface.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 *  DTD for Fawkes interfaces
 *
 *  Created: Wed Oct 11 00:57:30 2006
 *  Copyright  2006-2009  Tim Niemueller [www.niemueller.de]
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Library General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
-->
<!ELEMENT interface (constants?, data, message*)>
<!ATTLIST interface
	  name    CDATA  #REQUIRED
	  author  CDATA  #IMPLIED
	  created CDATA  #IMPLIED
	  year    CDATA  #IMPLIED>

  <!ELEMENT constants ((constant | enum)+)>
    <!ELEMENT constant (#PCDATA)>
    <!ATTLIST constant
	      type   CDATA  #REQUIRED
	      name   CDATA  #REQUIRED
	      value  CDATA  #REQUIRED>

    <!ELEMENT enum (comment, item+)>
    <!ATTLIST enum
	      name  CDATA  #REQUIRED>

      <!ELEMENT item (#PCDATA)>
      <!ATTLIST item
		name  CDATA  #REQUIRED>

  <!ELEMENT data (comment, (field | pseudomap | ref)+)>

    <!ELEMENT comment (#PCDATA)>

    <!ELEMENT pseudomap (comment, mapref+)>
    <!ATTLIST pseudomap
	      type      CDATA  #REQUIRED
	      keytype CDATA  #REQUIRED
	      name      CDATA  #REQUIRED>

    <!ELEMENT mapref (#PCDATA)>
    <!ATTLIST mapref
	      key      CDATA  #REQUIRED>

    <!ELEMENT field (#PCDATA)>
    <!ATTLIST field
	      type       CDATA  #REQUIRED
	      name       CDATA  #REQUIRED
	      flags      CDATA  #IMPLIED
	      length     CDATA  #IMPLIED
	      validfor   CDATA  '5'
	      default    CDATA  #IMPLIED
	      datafield  CDATA  #IMPLIED>

    <!ELEMENT ref (#PCDATA)>

  <!ELEMENT message (comment, (field | ref)*)>
  <!ATTLIST message
	    name  CDATA  #REQUIRED>

=== sj/fawkresrobotics-fawkes-copy/src/libs/interfaces/SpeechRecognitionInterface.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interface SYSTEM "interface.dtd">
<interface name="SpeechRecognitionInterface" author="Tim Niemueller and Masrur Doostdar" year="2009">
  <data>
    <comment>
      The interface provides access to a spech recognition facility.
    </comment>
    <field type="string" length="1024" name="text">
      Last spoken string. Must be properly null-terminated.
    </field>
    <field type="uint32" name="counter">
      Counter for messages. Increased after each new recognized string.
    </field>
    <field type="bool" name="processing">
      True, if the the speech recognition is currently processing.
    </field>
    <field type="bool" name="enabled">
      True, if speech processing is currently enabled, false otherwise.
    </field>
  </data>
  <message name="Reset">
    <comment>Orders the given text to be spoken.</comment>
  </message>
  <message name="SetEnabled">
    <comment>Orders the given text to be spoken.</comment>
    <ref>enabled</ref>
  </message>
</interface>

=== sj/fawkresrobotics-fawkes-copy/src/libs/interfaces/Position3DInterface.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interface SYSTEM "interface.dtd">
<interface name="Position3DInterface" author="Tim Niemueller" year="2011">
  <data>
    <comment>
      Storage for a 3D pose in Euclidean space.
    </comment>
    <field type="string" length="32" name="frame">
      Reference coordinate frame for the data.
    </field>
    <field type="int32" name="visibility_history">
      The visibilitiy history indicates the number of consecutive positive or negative
      sightings. If the history is negative, there have been as many negative sightings
      (object not visible) as the absolute value of the history. A positive value denotes
      as many positive sightings. 0 shall only be used during the initialization of the
      interface or if the visibility history is not updated.
    </field>
    <field type="double" length="4" name="rotation">
      Rotation quaternion relative to reference frame, ordered as (x, y, z, w).
    </field>
    <field type="double" length="3" name="translation">
      Translation vector from the reference frame's origin, ordered as (x, y, z).
    </field>
    <field type="double" length="36" name="covariance">
      Row-major representation of the 6x6 covariance matrix.
      The orientation parameters use a fixed-axis representation.
      In order, the parameters are:
      (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)
    </field>
  </data>
</interface>

=== sj/fawkresrobotics-fawkes-copy/src/plugins/laser-cluster/interfaces/LaserClusterInterface.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interface SYSTEM "interface.dtd">
<interface name="LaserClusterInterface" author="Tim Niemueller" year="2013">
  <constants>
    <enum name="SelectionMode">
      <comment>
        Enumeration defining the possible cluster selection modes.
      </comment>
      <item name="SELMODE_MIN_ANGLE">
	Choose the cluster with the minimum angle difference from 0 degrees.
      </item>
      <item name="SELMODE_MIN_DIST">
	Choose the cluster with the minimum distance in X direction of
	the reference frame (typically forward).
      </item>
    </enum>
  </constants>

  <data>
    <comment>Laser cluster parameterization.</comment>
    <field type="float" name="max_x">Maximum distance in X coordinate
    of sensor frame.</field>
    <field type="SelectionMode" name="selection_mode">
      Current cluster selection mode.
    </field>
  </data>
  <message name="SetMaxX">
    <comment>Set maximum distance in X coordinate of sensor frame.</comment>
    <ref>max_x</ref>
  </message>
  <message name="SetSelectionMode">
    <comment>Set desired cluster selection mode.</comment>
    <ref>selection_mode</ref>
  </message>
</interface>

=== sj/fawkresrobotics-fawkes-copy/src/libs/interfaces/GameStateInterface.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interface SYSTEM "interface.dtd">
<interface name="GameStateInterface" author="Tim Niemueller" year="2008">
  <constants>
    <!-- MSL game states, more generic to soccer -->
    <constant type="uint32" value="0" name="GS_FROZEN">Frozen, nothing moves.</constant>
    <constant type="uint32" value="1" name="GS_PLAY">Play, normal play</constant>
    <constant type="uint32" value="2" name="GS_KICK_OFF">Kick off</constant>
    <constant type="uint32" value="3" name="GS_DROP_BALL">Referee drops ball, both teams can wrestle for the ball</constant>
    <constant type="uint32" value="4" name="GS_PENALTY">Penalty kick</constant>
    <constant type="uint32" value="5" name="GS_CORNER_KICK">Corner kick</constant>
    <constant type="uint32" value="6" name="GS_THROW_IN">Throw in</constant>
    <constant type="uint32" value="7" name="GS_FREE_KICK">Free kick</constant>
    <constant type="uint32" value="8" name="GS_GOAL_KICK">Goal kick</constant>
    <constant type="uint32" value="9" name="GS_HALF_TIME">Half time</constant>

    <!-- SPL game states, game process state machine -->
    <constant type="uint32" value="0" name="GS_SPL_INITIAL">Initial setup phase.</constant>
    <constant type="uint32" value="1" name="GS_SPL_READY">Move to kick-off positions.</constant>
    <constant type="uint32" value="2" name="GS_SPL_SET">Wait for kick-off.</constant>
    <constant type="uint32" value="3" name="GS_SPL_PLAY">Play!</constant>
    <constant type="uint32" value="4" name="GS_SPL_FINISHED">Game or Half-time is finished</constant>

    <enum name="if_gamestate_team_t">
      <comment>
        Enumeration defining the different teams. Keep in sync with
	worldinfo_gamestate_team_t.
      </comment>
      <item name="TEAM_NONE">No team, not team-specific</item>
      <item name="TEAM_CYAN">Cyan team</item>
      <item name="TEAM_MAGENTA">Magenta team</item>
      <item name="TEAM_BOTH">Both teams</item>
    </enum>
    <enum name="if_gamestate_goalcolor_t">
      <comment>
        Enumeration defining the different teams. Keep in sync with
	worldinfo_gamestate_goalcolor_t.
      </comment>
      <item name="GOAL_BLUE">Blue goal</item>
      <item name="GOAL_YELLOW">Yellow goal</item>
    </enum>
    <enum name="if_gamestate_half_t">
      <comment>
        Enumeration defining the different teams. Keep in sync with
	worldinfo_gamestate_half_t.
      </comment>
      <item name="HALF_FIRST">First half</item>
      <item name="HALF_SECOND">Second half</item>
    </enum>
    <enum name="if_gamestate_role_t">
      <comment>
        Enumeration defining the different robot roles. Keep in sync with
	worldinfo_gamestate_role_t.
      </comment>
      <item name="ROLE_GOALIE">Goalie</item>
      <item name="ROLE_DEFENDER">Defender</item>
      <item name="ROLE_MID_LEFT">Midfield left</item>
      <item name="ROLE_MID_RIGHT">Midfield right</item>
      <item name="ROLE_ATTACKER">Attacker</item>
    </enum>
  </constants>
  <data>
    <comment>
      This interface provides access to the current game state. It is closely related to
      the WorldInfo network protocol.
      @see WorldInfoTransceiver
    </comment>
    <field type="uint32" name="game_state">Current game state</field>
    <field type="if_gamestate_team_t" name="state_team">Team referred to by game state</field>
    <field type="if_gamestate_team_t" name="our_team">Our team color</field>
    <field type="if_gamestate_goalcolor_t" name="our_goal_color">Our own goal color</field>
    <field type="if_gamestate_half_t" name="half">Current game half</field>
    <field type="bool" name="kickoff">Whether we have kickoff</field>
    <field type="if_gamestate_role_t" name="role">Current role of this robot</field>
    <field type="uint32" name="score_cyan">Score of team cyan</field>
    <field type="uint32" name="score_magenta">Score of team magenta</field>
  </data>
  <message name="SetTeamColor">
    <comment>Set color of own team</comment>
    <ref>our_team</ref>
  </message>
  <message name="SetKickoff">
    <comment>Set whether we have kickoff</comment>
    <ref>kickoff</ref>
  </message>
  <message name="SetStateTeam">
    <comment>Set the team the playmode applies to.</comment>
    <ref>state_team</ref>
  </message>
</interface>

=== sj/fawkresrobotics-fawkes-copy/src/plugins/perception/pcl-db/interfaces/PclDatabaseRetrieveInterface.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interface SYSTEM "interface.dtd">
<interface name="PclDatabaseRetrieveInterface" author="Tim Niemueller" year="2012-2013">
  <data>
    <comment>
      Instruct the pcl-db-retrieve plugin and receive information.
    </comment>
    <field type="uint32" name="msgid">
      The ID of the message that is currently being processed, or 0 if
      no message is being processed.
    </field>
    <field type="bool" name="final">
      True, if the last goto command has been finished, false if it is
      still running.
    </field>
    <field type="string" length="256" name="error">
      Error description if reconstruction fails.
    </field>
  </data>
  <message name="Retrieve">
    <comment>Order the merging of point clouds</comment>
    <field type="int64" name="timestamp">
      Timestamp for which to retrieve the most recent point clouds.
    </field>
    <field type="string" length="64" name="database">
      Database name from which to read the point clouds. If empty will
      use plugin-configured default.
    </field>
    <field type="string" length="128" name="collection">
      Collection name from which to read the point clouds. May NOT
      include the database name.
    </field>
    <field type="string" length="64" name="target_frame">
      Coordinate frame to which to transform the output point cloud.
      The transformation will be done through a fixed frame specified
      in the plugin config. If empty, no transformation is
      performed. If set to "SENSOR" will convert to the sensor frame
      specified in the plugin config.
    </field>
    <field type="bool" name="original_timestamp">
      Set to true to set the original timestamp on the point cloud,
      false (default) to publish with current time.
    </field>
  </message>
</interface>

=== sj/fawkresrobotics-fawkes-copy/src/libs/interfaces/CameraControlInterface.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interface SYSTEM "interface.dtd">
<interface name="CameraControlInterface" author="Tim Niemueller" year="2014">
  <constants>
    <enum name="Effect">
      <comment>
        Enumeration defining the possible effects. A camera must not necessarily
        implement all.
      </comment>
      <item name="EFF_NONE">No effect.</item>
      <item name="EFF_PASTEL">Pastel colors.</item>
      <item name="EFF_NEGATIVE">Negative/Positive Reversal.</item>
      <item name="EFF_BW">Monochrome Image.</item>
      <item name="EFF_SOLARIZE">Enhanced Contrast.</item>
    </enum>
  </constants>

  <data>
    <comment>
    </comment>
    <field type="Effect" name="effect">Currently active effect.</field>
    <field type="bool"   name="effect_supported">Are effects supported?</field>
    <field type="uint32" name="zoom">Current zoom setting.</field>
    <field type="bool"   name="zoom_supported">Is zooming supported?</field>
    <field type="uint32" name="zoom_max">Maximum zoom value</field>
    <field type="uint32" name="zoom_min">Minimum zoom</field>
    <field type="bool"   name="mirror">Is the image mirrored?</field>
    <field type="bool"   name="mirror_supported">Is mirroring supported?</field>
  </data>

  <message name="SetEffect">
    <comment>Set an effect.</comment>
    <ref>effect</ref>
  </message>

  <message name="SetZoom">
    <comment>Set zoom value.</comment>
    <ref>zoom</ref>
  </message>

  <message name="SetMirror">
    <comment>Set mirror state.</comment>
    <ref>mirror</ref>
  </message>
</interface>

=== sj/fawkresrobotics-fawkes-copy/src/libs/interfaces/SpeechSynthInterface.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interface SYSTEM "interface.dtd">
<interface name="SpeechSynthInterface" author="Tim Niemueller" year="2008">
  <data>
    <comment>
      The interface provides access to a spech synthesizer facility.
      On systems that support this feature strings can be ordered for
      synthesis and audio output. Multiple messages ordering speech
      should be enqueued and processed one after another by providers.
    </comment>
    <field type="string" length="1024" name="text">
      Last spoken string. Must be properly null-terminated.
    </field>
    <field type="uint32" name="msgid">
      The ID of the message that is currently being processed,
      or 0 if no message is being processed.
    </field>
    <field type="bool" name="final">
      True, if the last text has been spoken, false if it is still running.
    </field>
    <field type="float" name="duration">
      Length in seconds that it takes to speek the current text, -1 if
      unknown. This is the total duration of the current string, *not* the
      duration of already spoken or yet to speak text!
    </field>
  </data>
  <message name="Say">
    <comment>Orders the given text to be spoken.</comment>
    <ref>text</ref>
  </message>
</interface>

=== sj/fawkresrobotics-fawkes-copy/src/libs/interfaces/SwitchInterface.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interface SYSTEM "interface.dtd">
<interface name="SwitchInterface" author="Tim Niemueller" year="2008">
  <data>
    <comment>
      This interface provides access to LEDs. The interface controls
      an intensity value between 0.0 (off) and 1.0 (on, max
      intensity). LEDs that do not support intensity setting can only
      be set to on and off.
    </comment>
    <field type="bool" name="enabled">
      True if the switch is currently enabled.
    </field>
    <field type="float" name="value">
      If switches support multiple states these can be indicated with
      this value. For example for a switch that notes the intensity it
      could be a value in the valid range.
    </field>
    <field type="float" name="history">
      This value records the number of seconds a switch has been
      enabled continuously -- or not. The time is recorded in
      seconds. A positive value indicates time the switch was turned
      on, a negative value indicates the time (when converted to the
      absolute value) the button has not been pressed. Zero means
      "just initialized".
    </field>
    <field type="uint32" name="short_activations">
      Number of consecutive short clicks (turned on). Can be used to recognize
      patterns of clicks. This is an optional field.
    </field>
    <field type="uint32" name="long_activations">
      Number of consecutive short clicks (turned on). Can be used to recognize
      patterns of clicks. This is an optional field.
    </field>
    <field type="uint32" name="activation_count">
      Number that is to be incremented whenever a short or long activation
      happened. Can be used to decide if a change in status happened.
    </field>
  </data>
  <message name="Set">
    <comment>For switches that support setting via software this
      message allows for setting the current state.</comment>
    <ref>enabled</ref>
    <ref>value</ref>
  </message>
  <message name="EnableSwitch">
    <comment>For switches that support setting via software this
      message turns the switch on.</comment>
  </message>
  <message name="DisableSwitch">
    <comment>For switches that support setting via software this
      message turns the switch off.</comment>
  </message>
  <message name="EnableDuration">
    <comment>Enable switch for a specified duration only. The value
      can optionally be set. Note that not all SwitchInterface writers
      must or can support this.
    </comment>
    <field type="float" name="duration">Duration in seconds for which
    the switch should be enabled.</field>
    <ref>value</ref>
  </message>
</interface>
